### ISSUE TITLE
[Enhancement] Utilize web-optimized image formats

### ISSUE THREAD

**Issue by Vyogami** [pranjal-barnwal/minimal-kiwi#1]
Use the WebP format for asset images to improve loading speed.

`Ref:`

- https://developers.google.com/speed/webp#:~:text=WebP%20is%20a%20modern%20image,that%20make%20the%20web%20faster.

**Comment by pranjal-barnwal** [comment]
Sure, we can work on that part @Vyogami 
If you would like to make change & contribute, then you can also create a Pull Request.

**Comment by Vyogami** [comment]
I don't wish to work on this issue, but Kudos to you :)

**Comment by pranjal-barnwal** [comment]
Update to .webp formats
