### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by vanja-san** [pranjal-barnwal/minimal-kiwi#5]
**Describe the bug**
The context menu is too unbalanced in color.

**To Reproduce**
`None`

**Expected behavior**
- Make the background of the context menu like the left panel, i.e. it will become darker, which will make it stand out better against the background of the code area. Make white lines (separators) and the text itself less bright.

- (Optional) Add borders for the context menu (again, barely visible).

- (Optional) See how it will look without separators, maybe remove them altogether or make them transparent!?

**Screenshots**
<img src="https://github.com/user-attachments/assets/74cb36c6-40e9-41d7-b82c-8363fd564fab" width="460">

**Computer information (please complete the following information):**
- OS edition: Windows 11 Pro
- OS build: 22631.4169
- Extension Version 1.2.0
- VSCode version 1.94.0

**Additional context**
`Translated by machine translation`

**Comment by pranjal-barnwal** [comment]
**_Thank you so much @vanja-san✌️_** for pointing out a valid issue.
I will add a patch for this issue in the next release.

**Comment by vanja-san** [comment]
@pranjal-barnwal and the comments broken!
[IMG20241006204559.jpg](https://github.com/user-attachments/assets/ddf92a9a-c8c8-4f53-871e-5eb97154fe50)
![IMG20241006204611.jpg](https://github.com/user-attachments/assets/af44711f-587d-4a11-bcb3-dfd55f45f411)

**Comment by vanja-san** [comment]
@pranjal-barnwal Well, it's more here than in a separate post. I meant that the block with the comment is too much highlighted in bright color, which makes the code a bit blended.
ℹ️ The comment above, is a written comment not manually, but from the Flutter SDK!

Minimal Kiwi (Note the comment and the code):
![изображение](https://github.com/user-attachments/assets/72f56fcc-0fbc-46c6-a785-fa165b380762)

Material Theme (example):
![изображение](https://github.com/user-attachments/assets/73e342d1-117a-4a07-b3bd-670e0f0bbf00)

**Comment by pranjal-barnwal** [comment]
Got it, 
Have released a new version: [1.7.0](https://marketplace.visualstudio.com/items?itemName=PranjalKumar.minimal-kiwi), and have fixed both the issues.

Thank you for using Minimal Kiwi 
![HappyPikachuPikachuYesGIF](https://github.com/user-attachments/assets/b71c6b94-ffd3-4c3d-ae7d-f177a0090bd1)
